### ISSUE TITLE
Example project error in MacOS

### ISSUE THREAD

**Issue by Anarr** [riok/Kreya#110]
{
  "kreyaVersion": "1.8.1",
  "platform": "MacIntel",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)"
}

LibGit2Sharp.LibGit2SharpException: unsupported URL protocol
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in /_/LibGit2Sharp/Core/Proxy.cs:line 278
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in /_/LibGit2Sharp/Repository.cs:line 793
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath) in /_/LibGit2Sharp/Repository.cs:line 727
   at Kreya.Core.Projects.ProjectService.LoadExampleProject(String remoteRepositoryPath)
   at Kreya.UI.Projects.ProjectUiService.OpenExampleProject()
   at SpiderEye.Bridge.ApiMethod.InvokeAsync(Object instance, Object parameter)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.ResolveCall(String id, String parameters)

**Comment by ni507** [comment]
Thank you for your report.

The example project is cloned from the github repository with `https`. Can you try to clone the example project with a manual call on your console with `git clone https://github.com/riok/Kreya.git`, does this work?

And maybe you have some local git configurations that prevent an `https` call?

**Comment by CommonGuy** [comment]
As no further information has been provided, I'm going to close this issue.
