### ISSUE TITLE
Kreya displaying a black screen on Ubuntu 22.04 (Gnome Wayland)

### ISSUE THREAD

**Issue by eh-cevt** [riok/Kreya#112]
**Describe the bug**
When opening Kreya (both snap version and tarball) it only displays a black screen.

**To Reproduce**
1. Open Kreya on Ubuntu 22.04

**Expected behavior**
That Kreya would display some interface items more than the menu bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/103568930/199214433-425025a5-605e-4b55-8cfe-bec8a8e48c86.png)

**Environment (if possible, copy the information from the error dialog or the About menu):**
About menu is also a black screen.

- OS: Ubuntu 22.04 Gnome Wayland
- Kreya Version: 1.8.1 (tarball and snap) and 1.9.0-alpha.2 (snap)
```
$ uname -a
Linux csegotnd2214kf4 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional context**
When opening the about page the following shows up in the terminal:
```
$ kreya

** (kreya:159315): CRITICAL **: 11:37:02.033: Cannot register URI scheme spidereye more than once
```

**Comment by eh-cevt** [comment]
Tested with Gnome with X.Org with the same results.

**Comment by CommonGuy** [comment]
Thanks for your detailed bug reports. Could you post the content of `/home/{your username}/.config/kreya.log`? Are there any other errors in the console?
It looks like you have the dark theme enabled. Could you try opening Kreya with the default theme and see whether that works?

**Comment by eh-cevt** [comment]
I wiped the `.config/Kreya` directory and reran Kreya (1.8.1 tarball) but it only created a db file.

I reinstalled the snap version (1.9.0-alpha.2) and checked `snap/kreya/current/.config/Kreya/kreya.log`. It contained more details:

```
2022-11-02 09:15:14.115 +01:00 [ERR] Error getting clipboard text
System.Exception: Could not execute process. Command line: bash -c "xsel -o --clipboard  > /tmp/tmpSXjR89.tmp".
Output: 

Error: bash: xsel: command not found


   at BashRunner.Run(String commandLine) in /_/src/TextCopy/BashRunner.cs:line 42
   at LinuxClipboard.InnerGetText(String tempFileName) in /_/src/TextCopy/LinuxClipboard_2.1.cs:line 87
   at LinuxClipboard.GetTextAsync(CancellationToken cancellation) in /_/src/TextCopy/LinuxClipboard_2.1.cs:line 70
   at Kreya.Core.Clipboard.ClipboardEvents.TryGetText()
```

**Comment by CommonGuy** [comment]
Thanks for your feedback, we'll look into this

**Comment by CommonGuy** [comment]
Could you open "Help" -> "Show open source licenses..." in the Kreya menu? Is that window also blank or are the licenses displayed?

**Comment by eh-cevt** [comment]
The licenses are displayed in that window.

**Comment by CommonGuy** [comment]
Thanks for verifying! I managed to reproduce the issue, but only when I have an invalid system language set.

Does the same apply to you? What is the content of the`$LANG`  environment variable on your system? And does launching Kreya via
```
LANG=en_US.UTF-8 kreya
```

work?

**Comment by eh-cevt** [comment]
That is the solution to the problem! :sweat_smile:

I ran
```bash
$ echo $LANG
C.UTF-8
```

Running with `LANG=en_US.UTF-8` works! :tada:

**Comment by eh-cevt** [comment]
Although, it gives warnings:
```
$ LANG=en_US.UTF-8 kreya

(process:239253): Gtk-WARNING **: 08:51:10.678: Locale not supported by C library.
	Using the fallback 'C' locale.

(process:239304): Gtk-WARNING **: 08:51:11.736: Locale not supported by C library.
	Using the fallback 'C' locale.
```

Running with `LANG=C` gives no warnings :sweat_smile:

**Comment by CommonGuy** [comment]
Great!

It seems to happen only on systems where "C" is used as the default language and some language packs may not be installed. We will fix this in the next release. Meanwhile, setting a language can be used as a workaround

**Comment by CommonGuy** [comment]
This should be fixed in Kreya 1.10, which we just released.

**Comment by eliliam** [comment]
Sorry to bump this, but I am having the same exact issue. I have tested the above fix and it did not seem to work for me, nor are there any logs generated in `~/.config/Kreya/kreya.log`(just an empty file). For me when I go to the about menu via the menu bar(which is still visible) it pops up a black screen as well. This is running bog standard X11 on Arch as well.
![image](https://github.com/riok/Kreya/assets/14301439/b6cfabc6-056b-4e38-a5e1-9abfdcd6c79d)

One thing I did notice but think is unrelated, is when I opened the About menu I was met with some logs in the terminal that I ran `kreya` in:
```
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 600x671: Invalid argument
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 600x671: Invalid argument
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 600x671: Invalid argument
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 370x391: Invalid argument
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 370x391: Invalid argument
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 370x391: Invalid argument
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 370x391: Invalid argument
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 370x391: Invalid argument
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 370x391: Invalid argument
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
```

**Comment by CommonGuy** [comment]
@eliliam That is probably an unrelated, new issue... Seems like it is a problem with Linux + Nvidia. Maybe https://github.com/ValveSoftware/gamescope/issues/704 or https://github.com/ValveSoftware/gamescope/issues/816 can help?

Otherwise, please open a new issue so we can analyze this
