### ISSUE TITLE
Failed to initialize Kreya

### ISSUE THREAD

**Issue by matusbielik** [riok/Kreya#122]
**Describe the bug**
The Kreya doesn't start at all when clicked on on launcher. When called as command in terminal, the program outputs following stacktrace:
```
 ~ kreya
Failed to initialize Kreya: System.InvalidOperationException: Could not initialize GTK+
   at SpiderEye.Linux.GtkApplication.Init()
   at SpiderEye.Linux.GtkApplication..ctor()
   at SpiderEye.Linux.LinuxApplication.Init()
   at SpiderEye.Native.SpiderEyeInitializer.Init()
   at Kreya.UI.UiServices.AppUiServices.RunApp(String project)
   at Kreya.UI.Program.Main(String[] args)
Unhandled exception. System.InvalidOperationException: Application has not been initialized yet. Call LinuxApplication.Init() first.
   at SpiderEye.Application.CheckInitialized()
   at SpiderEye.Application.InvokeSafely(Action action)
   at SpiderEye.Application.Invoke[T](Func`1 function)
   at Kreya.UI.UiServices.AppUiServices.ExitWithError(ExitCodes exitCode, String msgTemplate, Object[] msgArgs)
   at Kreya.UI.Program.Main(String[] args)
[1]    577756 abort      kreya
```

**To Reproduce**
1. Start Kreya from terminal

**Expected behavior**
Kreya should start

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Debian 11, Gnome 3.38.5
 - Kreya Version: 1.9.0, installed through snap

**Additional context**
I am not aware of any changes to system and this is a sudden problem, Kreya was working on this machine before

**Comment by CommonGuy** [comment]
Does this error still happen? Do you have other applications that rely on GKT3 that run via snap, e.g. Firefox? Do they crash as well?

**Comment by CommonGuy** [comment]
Closing as no feedback was provided. Please reopen this issue with more information, so that we are able to reproduce the problem
