### ISSUE TITLE
Kreya crashes on requesting a grpc method

### ISSUE THREAD

**Issue by pooyajavan** [riok/Kreya#126]
{
  "kreyaVersion": "1.9.0",
  "platform": "Linux x86_64",
  "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
}

System.InvalidOperationException: Channel is configured with an HTTP transport doesn't support client-side load balancing or connectivity state tracking. The underlying HTTP transport must be a SocketsHttpHandler with no SocketsHttpHandler.ConnectCallback configured. The HTTP transport must be configured on the channel using GrpcChannelOptions.HttpHandler.
   at Grpc.Net.Client.GrpcChannel.ValidateHttpHandlerSupportsConnectivity()
   at Grpc.Net.Client.GrpcChannel..ctor(Uri address, GrpcChannelOptions channelOptions)
   at Grpc.Net.Client.GrpcChannel.ForAddress(Uri address, GrpcChannelOptions channelOptions)
   at Kreya.Grpc.Core.Utils.GrpcChannelBuilder.NewChannel(IGrpcChannelOptions options, IOperationAuthState authState, Nullable`1 clientCertId, Boolean infiniteTimeout)
   at Kreya.Grpc.Core.Invoker.GrpcInvokerFactory.GetInstance(MethodDescriptor methodDescriptor, GrpcInvokerOptions options, GrpcInvokerTracer tracer)
   at Kreya.Grpc.Core.Invoker.GrpcInvokerFactory.NewInvoker(IOperationWithDetail`2 operation, GrpcInvokerTracer tracer)
   at Kreya.Core.Api.Invoker.OperationInvokerFactoryAdapter`4.NewInvoker(IOperationWithDetail operationContent, InvokerEventTracer invokerEventTracer)
   at Kreya.Core.Invoker.InvokerService.InitializeInvokerAdapter(OperationInvoker invoker, IOperationWithDetail operation, EventTracer eventTracer)
   at Kreya.Core.Invoker.InvokerScope.<>c__DisplayClass20_0.<<Initialize>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Kreya.Core.Invoker.InvokerScope.Initialize()
   at Kreya.UI.Invoker.InvokerUiService.Start(Guid invokerId)
   at SpiderEye.Bridge.ApiMethod.InvokeAsync(Object instance, Object parameter)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.ResolveCall(String id, String parameters)

**Comment by CommonGuy** [comment]
What does your endpoint URL look like (you can substitute sensitive information with mock data)? It seems like you are using client-side load balancing which Kreya currently does not yet support. Would not be a huge change to implement this and knowing your endpoint URL would make this easier

**Comment by CommonGuy** [comment]
Closing as no feedback was provided. Please reopen this issue with more information, so that we are able to reproduce the problem
