### ISSUE TITLE
Error during duplication of operation

### ISSUE THREAD

**Issue by ByzantineKoala** [riok/Kreya#154]
{
  "kreyaVersion": "1.10.1",
  "releaseChannel": "stable",
  "osDescription": "Microsoft Windows 10.0.19043",
  "osVersion": "Microsoft Windows NT 10.0.19043.0",
  "osArch": "X64",
  "processArch": "X64",
  "runtimeIdentifier": "win10-x64",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.41"
}

System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\*******\*******\*******\Upload\Scripts\Query validation - Wrong data in "destination" for API upload in *******.krop'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.AsyncStreamReader(String path, Encoding encoding)
   at System.IO.File.InternalReadAllTextAsync(String path, Encoding encoding, CancellationToken cancellationToken)
   at Kreya.Data.FileSystem.FileService.ReadJson[TBase](String path, Func`2 concreteTypeProvider) in C:\dev\gitlab-runner\builds\ifF5m2AW\0\riokch\kreya\kreya\src\Kreya.Data\FileSystem\FileService.cs:line 79
   at Kreya.Data.OperationStorage.LoadOperationDetail(Project project, String operationPath) in C:\dev\gitlab-runner\builds\ifF5m2AW\0\riokch\kreya\kreya\src\Kreya.Data\OperationStorage.cs:line 85
   at Kreya.Core.Operations.OperationService.LoadOperationWithDetails(String operationPath) in C:\dev\gitlab-runner\builds\ifF5m2AW\0\riokch\kreya\kreya\src\Kreya.Core\Operations\OperationService.cs:line 148
   at Kreya.Core.Operations.OperationService.DeleteOperation(String path) in C:\dev\gitlab-runner\builds\ifF5m2AW\0\riokch\kreya\kreya\src\Kreya.Core\Operations\OperationService.cs:line 107
   at SpiderEye.Bridge.ApiMethod.InvokeAsync(Object instance, Object parameter)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.ResolveCall(String id, String parameters)

**Comment by CommonGuy** [comment]
The double quotes are not allowed in file names on Windows. That is why the duplication fails.

**Comment by ByzantineKoala** [comment]
Is there are" " in the Scripts Name this error occurs.
