### ISSUE TITLE
has an error when open the example project

### ISSUE THREAD

**Issue by FarmerChillax** [riok/Kreya#159]
**Report**
```
{
  "kreyaVersion": "1.10.1",
  "releaseChannel": "stable",
  "osDescription": "Darwin 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:06:26 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8112",
  "osVersion": "Unix 13.1.0",
  "osArch": "Arm64",
  "processArch": "Arm64",
  "runtimeIdentifier": "osx.13-arm64",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)"
}

LibGit2Sharp.LibGit2SharpException: unexpected http status code: 408
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in /_/LibGit2Sharp/Core/Proxy.cs:line 278
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in /_/LibGit2Sharp/Repository.cs:line 793
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath) in /_/LibGit2Sharp/Repository.cs:line 727
   at Kreya.Core.Projects.ProjectService.LoadExampleProject(String remoteRepositoryPath) in /builds/riokch/kreya/kreya/src/Kreya.Core/Projects/ProjectService.cs:line 184
   at Kreya.UI.Projects.ProjectUiService.OpenExampleProject() in /builds/riokch/kreya/kreya/src/Kreya.UI/Projects/ProjectUiService.cs:line 56
   at SpiderEye.Bridge.ApiMethod.InvokeAsync(Object instance, Object parameter)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.ResolveCall(String id, String parameters)
```
**To Reproduce**
1. Click on 'open the example project'
2. See error

**Expected behavior**

**Screenshots**

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: MacOS ventura 13.1

**Additional context**

**Comment by CommonGuy** [comment]
Opening the example project simply clones this repository (https://github.com/riok/Kreya).

It looks like you received a HTTP status code 408, which is a request timeout. Either GitHub had some problems or it is something on your end. I cannot reproduce this.

**Comment by FarmerChillax** [comment]
This may by my network problem.

**Comment by CommonGuy** [comment]
Thanks for the quick response.

If it still doesn't work, you can download this repository manually and then open the example project (in Kreya -> Open project -> navigate to the `example-project.krproj` file).

**Comment by BhandarkarPawan** [comment]
Did you find a fix to this issue? I have the same error when opening the example project...

**Comment by CommonGuy** [comment]
@BhandarkarPawan The example project is cloned from the GitHub repository with `https`. Can you try to clone the example project with a manual call on your console with `git clone https://github.com/riok/Kreya.git`, does this work? If it still doesn't work, you can download this repository manually and then open the example project (in Kreya -> Open project -> navigate to the `example-project.krproj` file).

Maybe you have some local git configurations that prevent cloning via `https`?
