### ISSUE TITLE
Error occured when example project opens

### ISSUE THREAD

**Issue by norabal** [riok/Kreya#191]
I tried "Open example project" then error occured.

![image](https://github.com/riok/Kreya/assets/5457058/9aee06f7-2d3f-4469-b79a-4038faed3d3e)

![image](https://github.com/riok/Kreya/assets/5457058/46c2e0b2-5ad3-42fa-9e0c-60d0f7bb8157)

{
  "kreyaVersion": "1.12.0",
  "releaseChannel": "stable",
  "osDescription": "Darwin 22.6.0 Darwin Kernel Version 22.6.0: Tue Nov  7 21:48:06 PST 2023; root:xnu-8796.141.3.702.9~2/RELEASE_X86_64",
  "osVersion": "Unix 13.6.3",
  "osArch": "X64",
  "processArch": "X64",
  "runtimeIdentifier": "osx.13-x64",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)"
}

LibGit2Sharp.LibGit2SharpException: unsupported URL protocol
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in /_/LibGit2Sharp/Core/Proxy.cs:line 278
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in /_/LibGit2Sharp/Repository.cs:line 793
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath) in /_/LibGit2Sharp/Repository.cs:line 727
   at Kreya.Core.Projects.ProjectService.LoadExampleProject(String remoteRepositoryPath)
   at Kreya.UI.Projects.ProjectUiService.OpenExampleProject()
   at SpiderEye.Bridge.ApiMethod.InvokeAsync(Object instance, Object parameter)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.ResolveCall(String id, String parameters)

**Comment by CommonGuy** [comment]
Thank you for your report.

The example project is cloned from the GitHub repository with `https`. Can you try to clone the example project with a manual call on your console with `git clone https://github.com/riok/Kreya.git`, does this work? If it still doesn't work, you can download this repository manually and then open the example project (in Kreya -> Open project -> navigate to the `example-project.krproj` file).

Maybe you have some local git configurations that prevent cloning via `https`?

**Comment by norabal** [comment]
Thank you for your response!

> you can download this repository manually and then open the example project (in Kreya -> Open project -> navigate to the example-project.krproj file).

This worked for me, and I can open example project.
