### ISSUE TITLE
Kreya create project error

### ISSUE THREAD

**Issue by ShinPoll** [riok/Kreya#205]
{
  "kreyaVersion": "1.13.1",
  "releaseChannel": "stable",
  "osDescription": "Microsoft Windows 10.0.19045",
  "osVersion": "Microsoft Windows NT 10.0.19045.0",
  "osArch": "X64",
  "processArch": "X64",
  "runtimeIdentifier": "win-x64",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
}

LibGit2Sharp.LibGit2SharpException: certificate revocation status could not be verified
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in /_/LibGit2Sharp/Core/Proxy.cs:line 278
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in /_/LibGit2Sharp/Repository.cs:line 824
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath) in /_/LibGit2Sharp/Repository.cs:line 758
   at Kreya.Core.Projects.ProjectService.LoadExampleProject(String remoteRepositoryPath)
   at Kreya.UI.Projects.ProjectUiService.OpenExampleProject()
   at SpiderEye.Bridge.ApiMethod.InvokeAsync(Object instance, Object parameter)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.ResolveCall(String id, String parameters)**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: [e.g. Windows 10]
 - Kreya Version [e.g. 1.0.0-beta.3]

**Additional context**

**Comment by CommonGuy** [comment]
Kreya tries to download the example project from this repository (https://github.com/riok/Kreya), which seems to fail for you.

You can try to manually download and open it
