### ISSUE TITLE
Kreya crashes for very fast actions at startup

### ISSUE THREAD

**Issue by AFract** [riok/Kreya#230]
Hello, 

Kreya Version : 
 {
  "kreyaVersion": "1.15.0-beta.1",
  "releaseChannel": "beta",
  "osDescription": "Microsoft Windows 10.0.19045",
  "osVersion": "Microsoft Windows NT 10.0.19045.0",
  "osArch": "X64",
  "processArch": "X64",
  "runtimeIdentifier": "win-x64",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
}

I have noticed that it is possible to make Kreya crash by several actions:

- Open it from its shortcut and very quickly click on the close window "X" button on top right of the newly opening window. 
It will interrupt loading but sometimes freeze the app instead of closing it: 
For example this window is completely frozen (I'll have to kill the process) : 
![image](https://github.com/riok/Kreya/assets/23377911/b7f0f303-5507-4659-85fd-1ef3bdd28d63)
If I attempt to close it (from Task Manager) :
![image](https://github.com/riok/Kreya/assets/23377911/caf958af-4214-439a-be38-303bb689d86a)

Here's the exception:

```
Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

************** Texte de l'exception **************
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateScope(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.RunInNewScope[TService](IServiceProvider sp, Action`1 action)
   at Kreya.Core.Utils.WindowInformationService.StoreWindowInformation(WindowInformation windowInformation)
   at Kreya.UI.UiServices.WindowUiStorage.StoreWindowInformation(String name, WindowInformation windowInformation)
   at SpiderEye.Windows.WinFormsWindow.SaveWindowInformation()
   at SpiderEye.Windows.WinFormsWindow.OnClosing(CancelEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)


************** Assemblys chargés **************
System.Private.CoreLib
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Kreya
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
System.Runtime
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Kreya.Core
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
Kreya.Data
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
Kreya.Common
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
System.Collections
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Linq
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Memory
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Kreya.Core.Api
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
Kreya.Importer
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
Kreya.Grpc.UI
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
Kreya.Rest.UI
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
Newtonsoft.Json
    Version de l’assembly : 13.0.0.0
    Emplacement : 
----------------------------------------
System.Text.Json
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
SpiderEye.Core
    Version de l’assembly : 0.1.0.0
    Emplacement : 
----------------------------------------
IdentityModel.OidcClient
    Version de l’assembly : 5.0.0.0
    Emplacement : 
----------------------------------------
netstandard
    Version de l’assembly : 2.1.0.0
    Emplacement : 
----------------------------------------
Kreya.UI.Api
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
System.ComponentModel
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Kreya.Data.Api
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
Microsoft.IdentityModel.Tokens
    Version de l’assembly : 7.4.0.0
    Emplacement : 
----------------------------------------
System.Security.Cryptography
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Bogus
    Version de l’assembly : 34.0.2.0
    Emplacement : 
----------------------------------------
Kreya.Infra.Api
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Caching.Memory
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Options
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Caching.Abstractions
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Scriban
    Version de l’assembly : 5.0.0.0
    Emplacement : 
----------------------------------------
Kreya.Infra
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
TextCopy
    Version de l’assembly : 1.0.0.0
    Emplacement : 
----------------------------------------
System.Collections.Concurrent
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.IdentityModel.Logging
    Version de l’assembly : 7.4.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Configuration
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Configuration.Json
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Configuration.CommandLine
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Configuration.Binder
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Text.RegularExpressions
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Reflection.Emit.Lightweight
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Threading
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Reflection.Emit.ILGeneration
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Reflection.Primitives
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Configuration.FileExtensions
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Primitives
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Private.Uri
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Net.Http
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Http
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Logging
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Diagnostics
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Diagnostics.DiagnosticSource
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
TestableIO.System.IO.Abstractions
    Version de l’assembly : 19.0.0.0
    Emplacement : 
----------------------------------------
TestableIO.System.IO.Abstractions.Wrappers
    Version de l’assembly : 19.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.EntityFrameworkCore
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Text.Encodings.Web
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Text.Encoding.Extensions
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Runtime.Intrinsics
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Numerics.Vectors
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.IO.RecyclableMemoryStream
    Version de l’assembly : 2.3.2.0
    Emplacement : 
----------------------------------------
System.Diagnostics.Tracing
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Logging.Configuration
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Logging.Console
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Extensions.Options.ConfigurationExtensions
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
ClearScript.Core
    Version de l’assembly : 7.4.1.0
    Emplacement : 
----------------------------------------
Kreya.Importer.Postman
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
Kreya.Importer.Insomnia
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
Kreya.Importer.Api
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
Kreya.Grpc.Core
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
Kreya.Grpc.Data
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
Kreya.Grpc.Protoc
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
Grpc.Core.Api
    Version de l’assembly : 2.0.0.0
    Emplacement : 
----------------------------------------
Google.Protobuf
    Version de l’assembly : 3.25.3.0
    Emplacement : 
----------------------------------------
Kreya.Rest.Core
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
Kreya.Rest.Data
    Version de l’assembly : 1.15.0.0
    Emplacement : 
----------------------------------------
System.Reflection.DispatchProxy
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Runtime.Loader
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Reflection.Emit
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
ProxyBuilder
    Version de l’assembly : 0.0.0.0
    Emplacement : 
----------------------------------------
SpiderEye.Native
    Version de l’assembly : 0.1.0.0
    Emplacement : 
----------------------------------------
Serilog
    Version de l’assembly : 2.0.0.0
    Emplacement : 
----------------------------------------
Serilog.Sinks.Async
    Version de l’assembly : 1.5.0.0
    Emplacement : 
----------------------------------------
Serilog.Extensions.Logging
    Version de l’assembly : 2.0.0.0
    Emplacement : 
----------------------------------------
System.Threading.ThreadPool
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Serilog.Sinks.File
    Version de l’assembly : 5.0.0.0
    Emplacement : 
----------------------------------------
System.IO.FileSystem
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Windows.Forms
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Windows.Forms.Primitives
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Runtime.InteropServices
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Diagnostics.TraceSource
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.ComponentModel.Primitives
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Drawing.Primitives
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Drawing.Common
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Threading.Thread
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Collections.Specialized
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Win32.Primitives
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Accessibility
    Version de l’assembly : 4.0.0.0
    Emplacement : 
----------------------------------------
System.Collections.Immutable
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Data.Sqlite
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Data.Common
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.ComponentModel.TypeConverter
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.EntityFrameworkCore.Sqlite
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.EntityFrameworkCore.Relational
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Linq.Expressions
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.EntityFrameworkCore.Abstractions
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Transactions.Local
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Version de l’assembly : 0.0.0.0
    Emplacement : 
----------------------------------------
System.IO.FileSystem.DriveInfo
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.IO.FileSystem.Watcher
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Threading.Channels
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Net.Primitives
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Net.Security
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Semver
    Version de l’assembly : 2.1.0.0
    Emplacement : 
----------------------------------------
RestEase
    Version de l’assembly : 1.6.4.0
    Emplacement : 
----------------------------------------
Mixpanel
    Version de l’assembly : 5.1.0.0
    Emplacement : 
----------------------------------------
System.Threading.Tasks
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Runtime.Extensions
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Reflection
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
IdentityModel
    Version de l’assembly : 5.2.0.0
    Emplacement : 
----------------------------------------
SQLitePCLRaw.core
    Version de l’assembly : 2.1.6.2060
    Emplacement : 
----------------------------------------
SQLitePCLRaw.batteries_v2
    Version de l’assembly : 2.1.6.2060
    Emplacement : 
----------------------------------------
SQLitePCLRaw.provider.e_sqlite3
    Version de l’assembly : 2.1.6.2060
    Emplacement : 
----------------------------------------
Microsoft.Windows.SDK.NET
    Version de l’assembly : 10.0.17763.24
    Emplacement : 
----------------------------------------
WinRT.Runtime
    Version de l’assembly : 2.0.0.0
    Emplacement : 
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.ComponentModel.Annotations
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Net.NetworkInformation
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.ObjectModel
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Linq.Queryable
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.IdentityModel.Tokens.Jwt
    Version de l’assembly : 7.4.0.0
    Emplacement : 
----------------------------------------
System.Xml.ReaderWriter
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Private.Xml
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Security.Claims
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.IdentityModel.JsonWebTokens
    Version de l’assembly : 7.4.0.0
    Emplacement : 
----------------------------------------
Microsoft.IdentityModel.Abstractions
    Version de l’assembly : 7.4.0.0
    Emplacement : 
----------------------------------------
System.Runtime.Serialization.Primitives
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Reflection.Extensions
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Version de l’assembly : 1.0.2478.35
    Emplacement : 
----------------------------------------
Microsoft.Web.WebView2.Core
    Version de l’assembly : 1.0.2478.35
    Emplacement : 
----------------------------------------
mscorlib
    Version de l’assembly : 4.0.0.0
    Emplacement : 
----------------------------------------
System
    Version de l’assembly : 4.0.0.0
    Emplacement : 
----------------------------------------
System.Drawing
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
Microsoft.Win32.SystemEvents
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Net.Sockets
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Threading.Overlapped
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Net.NameResolution
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Collections.NonGeneric
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Windows.Forms.resources
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Security.Principal.Windows
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Runtime.Serialization.Formatters
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Runtime.Numerics
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Globalization
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Text.Encoding
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Diagnostics.StackTrace
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------
System.Reflection.Metadata
    Version de l’assembly : 8.0.0.0
    Emplacement : 
----------------------------------------

************** Débogage JIT **************
```

---

- I have also noticed another case when Kreya crashes by opening very quickly two or more instances but I wasn't able to reproduce it to share the full exception, it was a Null Reference Exception.

Of course both are not "normal expected usages", so I would perfectly understand if you don't want to spend to much time to investigate these problems but I thought it could be useful at least to share them.

**Comment by CommonGuy** [comment]
Thanks for the detailed bug report. Regardless of whether it is "normal usage", this shouldn't happen :) I'll look into this

**Comment by CommonGuy** [comment]
This bugfix has just been released with Kreya 1.16
