### ISSUE TITLE
Error - Example Projekt - http: Der angegebene Host ist unbekannt. 

### ISSUE THREAD

**Issue by Fredi-Test** [riok/Kreya#245]
{
  "kreyaVersion": "1.15.0",
  "releaseChannel": "stable",
  "osDescription": "Microsoft Windows 10.0.19045",
  "osVersion": "Microsoft Windows NT 10.0.19045.0",
  "osArch": "X64",
  "processArch": "X64",
  "runtimeIdentifier": "win-x64",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0"
}

LibGit2Sharp.LibGit2SharpException: failed to resolve address for 
http: Der angegebene Host ist unbekannt. 
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in /_/LibGit2Sharp/Core/Proxy.cs:line 278
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in /_/LibGit2Sharp/Repository.cs:line 824
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath) in /_/LibGit2Sharp/Repository.cs:line 758
   at Kreya.Core.Projects.ProjectService.LoadExampleProject(String remoteRepositoryPath)
   at Kreya.UI.Projects.ProjectUiService.OpenExampleProject()
   at SpiderEye.Bridge.ApiMethod.InvokeAsync(Object instance, Object parameter)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.ResolveCall(String id, String parameters)

**Comment by CommonGuy** [comment]
Kreya tries to download the example project from GitHub (https://github.com/riok/Kreya/tree/master/example-project). It looks like your machine cannot connect to this host. We will improve this behavior in a future release.

As a workaround, you can download the example project manually

**Comment by Fredi-Test** [comment]
Super, vielen Dank, hat bestens funktioniert👍

Cheers,
Fredi

Manuel ***@***.***> schrieb am Fr., 19. Juli 2024, 15:31:

**Comment by CommonGuy** [comment]
Kreya now ships the example-project with the installation and no longer downloads it from the internet.
