### ISSUE TITLE
TLS self-signed certs are invalid on MacOS 15.0

### ISSUE THREAD

**Issue by ni507** [riok/Kreya#257]
TLS self-signed certs are invalid on MacOS 15.0. It worked before (MacOS 14.0) and it works on windows.

```
Interop+AppleCrypto+AppleCommonCryptoCryptographicException: The specified item is no longer valid. It may have been deleted from the keychain.
   at Interop.AppleCrypto.X509CopyWithPrivateKey(SafeSecCertificateHandle certHandle, SafeSecKeyRefHandle privateKeyHandle, SafeKeychainHandle targetKeychain)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(SafeSecKeyRefHandle privateKey)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(RSA privateKey)
   at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.CopyWithPrivateKey(X509Certificate2 certificate, RSA privateKey)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.ExtractKeyFromPem[TAlg](ReadOnlySpan`1 keyPem, String[] labels, Func`1 factory, Func`2 import)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPem(ReadOnlySpan`1 certPem, ReadOnlySpan`1 keyPem)
   at Kreya.Core.Certificates.Handler.KeyCertFile.KeyCertFileCertificateHandler.LoadCertificate(ICertificate`1 certificate)
```

**Screenshots**
![image (5)](https://github.com/user-attachments/assets/bb0ca363-753e-4f78-bca8-e098f95317af)

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: MacOS 15.0

**Comment by ni507** [comment]
This has been fixed in the latest beta version and will be released in the next stable version
