### ISSUE TITLE
Possible regression in 1.16b3 (Cannot access a disposed object exception)

### ISSUE THREAD

**Issue by AFract** [riok/Kreya#273]
Hello, 
With 1.16 beta 3, I was executing a REST GET operations (with no script, and ending by a 409 http error) when this error popped : 

![image](https://github.com/user-attachments/assets/bdd3eb4f-4149-46a5-8e66-f6422872628b)

It occurred only once, so not blocking at all. I just share this in case it could be helpful for continuous improvement of Kreya :) 

```
{
  "kreyaVersion": "1.16.0-beta.3",
  "releaseChannel": "beta",
  "osDescription": "Microsoft Windows 10.0.19045",
  "osVersion": "Microsoft Windows NT 10.0.19045.0",
  "osArch": "X64",
  "processArch": "X64",
  "runtimeIdentifier": "win-x64",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0"
}

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Collections.Concurrent.BlockingCollection`1[[System.Threading.Tasks.Task, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
   at System.Collections.Concurrent.BlockingCollection`1.CompleteAdding()
   at Kreya.Common.SingleThreadTaskScheduler.Dispose()
   at Kreya.Core.Invoker.InvokerScope.DisposeAsync()
   at Kreya.UI.Invoker.InvokerUiService.CleanInvokerScope(Guid invokerId)
   at Kreya.UI.Invoker.InvokerUiService.SendAllRequestsAndComplete(Guid invokerId)
   at SpiderEye.Bridge.ApiMethod.InvokeAsync(Object instance, Object parameter)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.ResolveCall(String id, String parameters)
```

**Comment by CommonGuy** [comment]
While I couldn't reproduce the bug, I fixed a possible race condition that could have lead to this. I suspect that this happened very rarely, as we did not change anything here in the last few releases.
