### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by B-Rab** [riok/Kreya#38]
OS: Windows 10

I have installed Kreya on several Macs without issue but I'm now trying to install on Windows. This issue is occurring on two separate windows machines but works on a third. Error below is displayed immediately upon opening the application. The error can be bypassed by clicking 'continue' but the top menu only displays Kreya and Help (no Project tab) so I can't configure anything. I tried to import an existing project but the importers can't be run. 

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.
************** Exception Text **************
System.InvalidOperationException: Sequence contains more than one element.
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Kreya.Data.AppInfoStorage.UpdateInfo(String currentVersion, AppReleaseChannel releaseChannel)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.RunInNewScope[TService,TResult](IServiceProvider sp, Func`2 action)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.RunInNewScope[TService,TResult](IServiceProvider sp, Func`2 action)
   at Kreya.Core.Updater.AutoUpdaterService.UpdateAppInfo()
   at Kreya.Core.Updater.AutoUpdaterService.StartCheckForUpdatesLoop(CancellationToken ct)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)

**Comment by CommonGuy** [comment]
There was a race condition in Kreya which results in the above error. It will be fixed in the next Kreya release.

As a workaround, you could delete the `kreya.db` file in `%APPDATA%\Kreya` and then restart Kreya. Note that this removes some locally stored data such as the recent projects, response history or locally stored environment data.

**Comment by CommonGuy** [comment]
Kreya v1.5 was just released, which includes a fix for this bug.
