### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by jerv13** [riok/Kreya#42]
**Describe the bug**
```
{
  "kreyaVersion": "1.5.0",
  "platform": "Win32",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 Edg/92.0.902.73"
}

System.ArgumentException: An item with the same key has already been added.
   at NJsonSchema.Collections.ObservableDictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NJsonSchema.Collections.ObservableDictionary`2.Add(TKey key, TValue value)
   at Kreya.Grpc.Core.Validation.ProtoJsonSchemaGenerator.BuildMessageSchemaFields(MessageDescriptor messageDescriptor, JsonSchema schema, IDictionary`2 definitions)
   at Kreya.Grpc.Core.Validation.ProtoJsonSchemaGenerator.BuildMessageSchema(MessageDescriptor messageDescriptor, IDictionary`2 definitions)
   at Kreya.Grpc.Core.Validation.ProtoJsonSchemaGenerator.GenerateJsonSchemaForMessage(MessageDescriptor descriptor)
   at Kreya.Grpc.Core.Operations.GrpcComputedDetailsLoader.LoadComputedDetails(String methodFqn, GrpcOperationComputedDetails details)
   at Kreya.Grpc.Core.Operations.GrpcComputedDetailsLoader.OperationLoaded(IOperationWithDetail`2 operation)
   at Kreya.Grpc.Data.StorageHooks.GrpcOperationStorageHook.OperationLoaded(IOperationWithDetail`2 operation)
   at Kreya.Data.OperationStorage.LoadOperationDetail(Project project, String operationPath)
   at Kreya.Core.Operations.OperationService.LoadOperationWithDetails(String operationPath)
   at Kreya.UI.Invoker.OperationUiService.LoadOperationWithDetails(String operationPath)
   at SpiderEye.Bridge.ApiMethod.InvokeAsync(Object instance, Object parameter)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.ResolveCall(String id, String parameters)
```

**To Reproduce**
1. Go to 'My Project'
2. Click on 'One of my service methods called "processAll"'
3. Scroll down to 'N/A'

**Expected behavior**

Expect the normal service method page to appear 

**Screenshots**

![image](https://user-images.githubusercontent.com/853222/129945506-e5078530-ae47-4697-a145-5f458c6af3a3.png)

**Environment (if possible, copy the information from the error dialog or the About menu):**
 - OS: Windows 10
 - Kreya Version 1.5.0

**Additional context**

I have many separate protos for several services in a shared namespace

**Comment by latonz** [comment]
Thank you for your bug report. Do you have proto files which lead to the error which you could share?

**Comment by CommonGuy** [comment]
Can you try this again with the newly released 1.6 version?
