### ISSUE TITLE
Key for ASCII valued metadata entry cannot have suffix indicating binary value

### ISSUE THREAD

**Issue by jossErnesto** [riok/Kreya#84]
I am trying to send a string in Metadata but I got this error:
`System.ArgumentException: Key for ASCII valued metadata entry cannot have suffix indicating binary value.
   at Grpc.Core.Utils.GrpcPreconditions.CheckArgument(Boolean condition, String errorMessage)
   at Grpc.Core.Metadata.Entry..ctor(String key, String value)
   at Kreya.Grpc.Core.Invoker.CallOptionsBuilder.BuildCallOptions(GrpcInvokerOptions options)
   at Kreya.Grpc.Core.Invoker.AbstractGrpcInvoker.Start()
   at Kreya.Core.Invoker.OperationInvoker.Start()
   at SpiderEye.Bridge.ApiMethod.InvokeAsync(Object instance, Object parameter)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.ResolveCall(String id, String parameters)`

The C# source code uses this method to convert from string to byte[]:
public virtual byte[] GetBytes (string s);
https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.getbytes?view=net-6.0

I would like to know how to send byte[] in Metadata
I tried to use this:
{{ string.base64_encode(...}}
but no luck.
The metadata key must have suffix indicating a binary value, that is a requirement.

**Comment by CommonGuy** [comment]
Hi! We just added support for binary request metadata. This feature will be available in the upcoming 1.8 release, which we'll release soon.

**Comment by latonz** [comment]
V1.8 has been released.
