### ISSUE TITLE
[ BUG ] - Request localhost grpc server

### ISSUE THREAD

**Issue by isasmendiagus** [riok/Kreya#86]
Trying to request my localhost grpc service I got this error

```
{
  "kreyaVersion": "1.7.0",
  "platform": "Linux x86_64",
  "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
}

System.ArgumentException: Address 'localhost:50053' doesn't have a host. Address should include a scheme, host, and optional port. For example, 'https://localhost:5001'.
   at Grpc.Net.Client.GrpcChannel..ctor(Uri address, GrpcChannelOptions channelOptions)
   at Grpc.Net.Client.GrpcChannel.ForAddress(Uri address, GrpcChannelOptions channelOptions)
   at Kreya.Grpc.Core.Utils.GrpcChannelBuilder.NewChannel(IGrpcChannelOptions options, Nullable`1 clientCertId)
   at Kreya.Grpc.Core.Invoker.GrpcInvokerFactory.GetInstance(MethodDescriptor methodDescriptor, GrpcInvokerOptions options)
   at Kreya.Grpc.Core.Invoker.GrpcInvokerFactory.NewInvoker(IOperationWithDetail`2 operation)
   at Kreya.Core.Api.Invoker.OperationInvokerFactoryAdapter`3.NewInvoker(IOperationWithDetail operationContent)
   at Kreya.Core.Invoker.InvokerService.CreateInvoker(String operationPath)
   at Kreya.Core.Invoker.InvokerScope.Create(String operationPath, IServiceProvider serviceProvider)
   at Kreya.Core.Invoker.InvokerScope.Create(String operationPath, IServiceProvider serviceProvider)
   at Kreya.UI.Invoker.InvokerUiService.CreateInvoker(String operationPath)
   at SpiderEye.Bridge.ApiMethod.InvokeAsync(Object instance, Object parameter)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.ResolveCall(String id, String parameters)

```

**Screenshots**
![image](https://user-images.githubusercontent.com/17660235/171830058-3f313a89-6ec9-4ef1-b4dc-203cc214c172.png)

**Comment by ni507** [comment]
Try to add `http://` or `https://`  to the address.
An address should include a scheme, host, and optional port. For example, `https://localhost:5001/`.
We will consider to allow an address without a scheme and prefix the address with `http://` in a future release.
